import Menubar from "@/components/menuBar";
import ModalCategoria from "@/components/modalCategoria";
import { EditIcon } from "@chakra-ui/icons";

import {
  Box,
  Button,
  Flex,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
  useBreakpointValue,
  useDisclosure,
} from "@chakra-ui/react";

import Head from "next/head";
import { useEffect, useState } from "react";

export default function CategoriaCliente() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [data, setData] = useState([]);
  const [dataEdit, setDataEdit] = useState({});

  const isMobile = useBreakpointValue({
    base: true,
    lg: false,
  });

  useEffect(() => {
    const db_categoria = localStorage.getItem("categoria")
      ? JSON.parse(localStorage.getItem.toString())
      : [];

    setData(db_categoria);
  }, [setData]);

  return (
    <>
      <Head>
        <title>Categoria de Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menubar />
        <Flex
          minHeight={"100vh"}
          width={"full"}
          align={"center"}
          justifyContent={"center"}
          backgroundColor={"gray.900"}
        >
          <Box
            width={"full"}
            maxWidth={"550px"}
            textAlign={"center"}
            boxShadow={"lg"}
            background={"gray.700"}
            borderRadius={"16px"}
          >
            <Box maxW={800} w="full" h="550px" py={10} px={2}>
              <Button
              borderRadius={"16px"}
              _hover={{
                bgcolor: "#1434A4",
              }}
                colorScheme="blue"
                onClick={() => [setDataEdit({}), onOpen()]}
              >
                Cadastrar Categoria
              </Button>

              <Box overflowY="auto" height="100%">
                <Table mt="6">
                  <Thead>
                    <Tr>
                      <Th maxW={isMobile ? 5 : 100} fontSize="20px">
                        Nome categoria
                      </Th>
                      <Th p={0}></Th>
                      <Th p={0}></Th>
                    </Tr>
                  </Thead>
                  <Tbody>
                    {data.map(({ name }, index) => (
                      <Tr
                        key={index}
                        cursor="pointer "
                        _hover={{ bg: "gray.100" }}
                      >
                        <Td maxW={isMobile ? 5 : 100}>{name}</Td>

                        <Td p={0}>
                          <EditIcon
                            fontSize={20}
                            onClick={() => [
                              setDataEdit({ name, index }),
                              onOpen(),
                            ]}
                          />
                        </Td>
                      </Tr>
                    ))}
                  </Tbody>
                </Table>
              </Box>
            </Box>
            {isOpen && (
              <ModalCategoria
                isOpen={undefined}
                onClose={undefined}
                data={undefined}
                setData={undefined}
                dataEdit={undefined}
              />
            )}
          </Box>
        </Flex>
      </main>
    </>
  );
}
