import {
  Box,
  Flex,
  Heading,
  Text,
  FormControl,
  FormLabel,
  Input,
  Button,
} from "@chakra-ui/react";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Cadastro de Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minHeight={"100vh"}
          width={"full"}
          align={"center"}
          justifyContent={"center"}
          backgroundColor={"gray.900"}
        >
          <Box
            px={12}
            py={12}
            width={"full"}
            maxWidth={"550px"}
            textAlign={"center"}
            boxShadow={"lg"}
            background={"gray.700"}
            borderRadius={"16px"}
          >
            <Heading>
              <Text color={"white"} fontSize={"28"}>
                Preencha o cadastro
              </Text>
            </Heading>
            <Box>
              <form action={""} autoComplete="off">
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>Nome Completo</FormLabel>
                  <Input
                    type="text"
                    name="nome"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"Nome Completo"}
                  />
                </FormControl>
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>E-mail</FormLabel>
                  <Input
                    type="email"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"examplo@email.com.br"}
                  />
                </FormControl>
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>CPF</FormLabel>
                  <Input
                    type="number"
                    maxLength={11}
                    name="cpf"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"99999999999"}
                  />
                </FormControl>
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>Endereço</FormLabel>
                  <Input
                    type="text"
                    name="endereco"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"Rua exemplo, 32 - RS"}
                  />
                </FormControl>
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>Telefone</FormLabel>
                  <Input
                    type="tel"
                    name="telefone"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"(99) 9999-9999"}
                  />
                </FormControl>
                <FormControl isRequired mt={"15"}>
                  <FormLabel color={"white"}>Data de Nascimento</FormLabel>
                  <Input
                    type="date"
                    border={"none"}
                    outline={"none"}
                    bgColor={"gray.800"}
                    focusBorderColor={"gray.600"}
                    color={"gray.200"}
                    placeholder={"99/99/9999"}
                  />
                </FormControl>
                <Button
                  mt={"15"}
                  type="submit"
                  colorScheme="blue"
                  w={"full"}
                  h={"12"}
                  borderRadius={"16px"}
                  _hover={{
                    bgcolor: "#1434A4",
                  }}
                >
                  Salvar
                </Button>
              </form>
            </Box>
          </Box>
        </Flex>
      </main>
    </>
  );
}
